# Configuration for Scaled Production Environment (Week 7-8)
# 40 machines, 50 families, focus on scaling efficiency

environment:
  n_machines: 40
  max_episode_steps: 1000
  max_valid_actions: 100
  
training:
  # Total training timesteps (increased for larger scale)
  total_timesteps: 2000000
  
  # Parallel environments
  n_envs: 8
  
  # PPO hyperparameters
  learning_rate: 0.0001
  batch_size: 512  # Larger batch for more stable learning
  n_epochs: 10
  clip_range: 0.2
  
  # Network architecture (larger for more complex state)
  network_arch: [512, 512, 256]
  
  # GAE parameters
  gamma: 0.99
  gae_lambda: 0.95
  
  # Entropy and value function coefficients
  ent_coef: 0.05
  vf_coef: 0.5
  max_grad_norm: 0.5
  
  # Steps per update
  n_steps: 4096
  
  # Random seed
  seed: 42

evaluation:
  # Evaluation frequency
  eval_freq: 10000
  n_eval_episodes: 5
  
  # Baseline comparison
  compare_baselines: true
  baseline_episodes: 10

logging:
  # Tensorboard logging
  tensorboard_log: "./tensorboard/scaled_production/"
  
  # Model checkpoints
  checkpoint_freq: 50000
  save_path: "./models/scaled_production/"
  
  # Results
  results_path: "./logs/scaled_production/"

# Reward weights (for future customization)
rewards:
  completion: 10.0
  importance_bonus: 20.0
  utilization_factor: 5.0
  load_balance_factor: 10.0
  setup_penalty_factor: 5.0
  urgency_high: 10.0
  urgency_medium: 5.0
  time_penalty: 0.1
  episode_bonus: 50.0
  efficiency_factor: 50.0
  utilization_bonus: 30.0

# Machine configuration
machines:
  # Machine type groupings for capabilities
  type_groups:
    specialized_cf: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    specialized_cp: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    specialized_cd_ch_cm: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
    universal: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42]
  
  # Setup time matrix (hours)
  setup_times:
    same_type: 0.1
    different_type_base: 0.3
    max_setup: 0.9

# Production constraints
constraints:
  # Working hours (from database in production)
  working_hours_per_day: 16.5  # 6:30 AM - 11:00 PM with breaks
  
  # Maintenance windows
  maintenance_day: 7  # Sunday
  maintenance_start_hour: 6
  maintenance_duration: 4
  
  # Urgency thresholds (days)
  high_urgency_threshold: 7
  medium_urgency_threshold: 14